[build]
base = "docs/"
publish = "public/"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
