theme = "hugo-theme-learn"
languageCode = "en-us"
title = "superluminar - Serverless Workshop"

[params]
editURL = "https://github.com/superluminar-io/cdk-java-workshop/edit/master/content/"
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-link'></i> Additional material"
url = "/links"
weight = 5

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
url = "https://github.com/superluminar-io/cdk-java-workshop"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> AWS CDK docs"
url = "https://docs.aws.amazon.com/cdk/api/latest/docs/aws-construct-library.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='far fa-copyright'></i> Impressum"
url = "/impressum"
weight = 30
